=== PingSharp/fernSchule_CSharp/CSH10/Lektion4/Box.dtd
<!--DTD zum XML-Dokument “Box.xml“-->
<!ELEMENT box (card)+>
<!ELEMENT card (keyword+,abstract?,content*,source?,createDate,date?)>
<!ELEMENT keyword (#PCDATA)>
<!ELEMENT abstact (#PCDATA)>
<!ELEMENT content (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT createDate (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ATTLIST card subject CDATA #REQUIRED>
<!ATTLIST content type (titel|text|quote|code|url|image) "text">

=== PingSharp/fernSchule_CSharp/CSH10/Lektion4/Box.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE box SYSTEM "C:\Users\Kahr_Zang\source\repos\CSH10\Lektion4\Box.dtd">
<box>
  <!--erste Karte-->
  <card subject="XML">
    <keyword>DTD</keyword>
    <keyword>Wikipedia</keyword>
    <abstact>Wie erstellt man eine DTD?</abstact>
    <content type="titel">Erst Struktur planen,dann umsetzen</content>
    <content type="text">Nicht immer reicht eine Anleitung aus,die in Wikipedia steht:</content>
    <content type="quote">Eine Dokumenttypdefinition(englisch Document Type Definition,DTD,auch SchemaDefinition
     oder DOCTYPE) ist ein Satz an Regeln,der benutzt wird,um Dokumente eines bestimmten Typs zu deklarieren.  
  </content>
    <content type="url">
      http://de.wikipedia.org/wiki/Dokumenttypdefinition
    </content>
    <source>Web</source>
    <createDate>20.05.2010</createDate>
    <date>20.05.2010</date>
</card>
</box>
